### ISSUE TITLE
Убрать из формы ссылку на новость

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#13]
![image](https://user-images.githubusercontent.com/52461010/70794466-579e7300-1da6-11ea-8345-b74c3e6f4b8a.png)

Поле автозаполняется, показывать его не надо, но в табличку нужно передавать

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после исправления бага.

**Comment by mytcat** [comment]
Done

**Comment by AlexUdodenko** [comment]
![image](https://user-images.githubusercontent.com/52461010/71172693-92525080-2269-11ea-9550-cd3ce18a7b1a.png)

после того, как убрали ссылку на новость из формы, ссылка перестала передаваться в файл с результатами

**Comment by mytcat** [comment]
Done
