### ISSUE TITLE
Сделать список инвесторов через запятую

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#14]
![image](https://user-images.githubusercontent.com/52461010/70796378-c7166180-1daa-11ea-81bd-29463a98d376.png)

Аналогично к тому, как реализованы Lead Investors и Partner Investors. чтоб при нажатии на разные куски текста всё добавлялось в одну ячейку (разделитель в стиле csv)

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после версии 1.61

**Comment by mytcat** [comment]
Done

**Comment by AlexUdodenko** [comment]
![image](https://user-images.githubusercontent.com/52461010/71172815-e6f5cb80-2269-11ea-99bd-24efdabb88bb.png)

тут результаты в ячейке перечислены просто через запятую обычную, а не разделителем csv. Если будет запись, содержащая запятую, получится некорректный результат в ячейке. например, имя фонда "Alexa Accelerator, Powered by Techstars"

**Comment by mytcat** [comment]
Done
