### ISSUE TITLE
Убрать всплывающий календарь в поле Announced Date

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#15]
![image](https://user-images.githubusercontent.com/52461010/70796736-ab5f8b00-1dab-11ea-8b95-e0e706ff56ed.png)

заполняется копи-пастом, всплывающий календарь будет только мешать

**Comment by mytcat** [comment]
@AlexUdodenko Будет исправлено в версии 1.61

**Comment by mytcat** [comment]
Done
