### ISSUE TITLE
Неактивность полей Lead Investors и Partner Investors

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#16]
Если нажимать на выделенные куски текста, они не будут переноситься в поля Lead Investors или Partner Investors, а будут появляться в последней активной ячейке

**Comment by mytcat** [comment]
@AlexUdodenko Баг. Будет исправлен в следующей версии (1.61)

**Comment by mytcat** [comment]
Done

**Comment by AlexUdodenko** [comment]
![image](https://user-images.githubusercontent.com/52461010/71172815-e6f5cb80-2269-11ea-99bd-24efdabb88bb.png)

тут результаты в ячейке перечислены просто через запятую обычную, а не разделителем csv. Если будет запись, содержащая запятую, получится некорректный результат в ячейке. например, имя фонда "Alexa Accelerator, Powered by Techstars"
