### ISSUE TITLE
Редактирование поля Pre-Money Valuation

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#17]
Нужно переименовать поле в "Valuation"
И прикрепить к полю стрелочку, из которой будет выпадать контекстное меню с вариантами дополнительного атрибута этого поля:
- Not Defined (стоит по умолчанию)
- Post-Money
- Pre-Money

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после версии 1.61

**Comment by mytcat** [comment]
Done
