### ISSUE TITLE
Добавление поля Revenue

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#18]
Нужно добавить поле "Revenue"
И прикрепить к полю стрелочку, из которой будет выпадать контекстное меню с вариантами дополнительного атрибута этого поля:
- Not Defined (стоит по умолчанию)
- ARR
- MRR
- AR
- MR

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после версии 1.61

**Comment by mytcat** [comment]
Done
