### ISSUE TITLE
Добавление поля Clients Amount

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#19]
Нужно добавить поле "Clients Amount"
И прикрепить к полю стрелочку, из которой будет выпадать контекстное меню с вариантами дополнительного атрибута этого поля:
- Not Defined (стоит по умолчанию)
- B2C
- B2B
- Enterprise

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после версии 1.61

**Comment by mytcat** [comment]
Done
