### ISSUE TITLE
Отключить переход по гиперссылкам

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#21]
![image](https://user-images.githubusercontent.com/52461010/70802708-cf769880-1dba-11ea-9745-627ffdbbe639.png)

При нажатии на выделенный в тексте "17zuoye", помимо добавления в форму этого слова, откроется гиперссылка. Можно ли отключить возникновение такого кейса? это сбивает юзера

**Comment by mytcat** [comment]
@AlexUdodenko Это новая фича. Будет в следующих релизах после версии 1.61

**Comment by mytcat** [comment]
Done

**Comment by ElizaLo** [comment]
Ещё нужно отключить скроллинг вверх при нажатии на тэг с гиперссылкой.
