### ISSUE TITLE
Сохранение области полезного текста в ячейку

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#22]
Когда юзер открывает новость, и экстеншн её анализирует, то он первым делом же выделяет со страницы, какой именно текст берётся для анализа. Нужно в отдельную ячейку таблицы с результатами сохранять этот текст.

**Comment by mytcat** [comment]
Насколько длинным может быть этот текст? Что юзер будет делать с ним после того, как он сохранится в отдельную ячейку?

**Comment by AlexUdodenko** [comment]
юзер ничего.  юзер даже не должен знать, что этот текст сохраняется.

текст нужен Саше, чтоб его нейронка понимала, из какого текста были сделаны какие выводы

**Comment by zhuker** [comment]
@mytcat текст статьи в ячейку == то что ты передаешь в spacy

**Comment by AlexUdodenko** [comment]
немного не то получилось. нужно сохранять в ячейку полный текст статьи, а не только выделенные слова. суть упражнения в том, чтоб понимать из какого текста были эти слова выделены

**Comment by mytcat** [comment]
Done
