### ISSUE TITLE
В поле «Clients Amount» неправильно указаны опции выбора

### ISSUE THREAD

**Issue by AlexUdodenko** [mytcat/Form-to-google-spreadsheet#25]
Вместо ARR, MRR, AR, MR должны быть указаны B2C Clients Amount, B2B Clients
Amount, Enterprise Clients Amount и Not Defined.

![image](https://user-images.githubusercontent.com/52461010/72113119-3b133d80-3348-11ea-9fe7-a0fc44e03d18.png)

**Comment by mytcat** [comment]
Fixed
