### ISSUE TITLE
Несколько раз можно внести одни и те же данные в поле

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#29]
<img width="1392" alt="Снимок экрана 2020-01-13 в 12 24 23" src="https://user-images.githubusercontent.com/36056528/72248447-dda91600-35ff-11ea-9b72-911625ef18ab.png">

Вносит дважды одни и те же данные во все поля, **кроме полей**: 

- **Lead Investors**
- **Partner Investors** 
- **Investors**

**Comment by mytcat** [comment]
Time Estimation: 30mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Fixed in v. 1.68
