### ISSUE TITLE
Кнопка "Fix" не работает

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#30]
<img width="1392" alt="Снимок экрана 2020-01-13 в 13 20 44" src="https://user-images.githubusercontent.com/36056528/72252289-acccdf00-3607-11ea-99b8-423225576694.png">

Вернее работает некорректно: при нажатии на кнопку **"Fix"** вносятся данные в таблицу с новой строки, а не вносит правки в нужную строку в таблице.

Как должна работать кнопка **"Fix"**:
1. Нажимаем на экстеншн.
2. Он вызывает таблицу.
3. Нажимаем на кнопку  **"Fix"**.
4. Подгружаются данные с датасета в поля таблицы.
5. Пользователь вносит изменения в таблицу: редактирует или дополняет данные.
6. Нажимает на кнопку  **"Fix"** (она меняет цвет с синего на зелёный) и вносит изменения в датасет (а не создаёт новую строку).

**Comment by mytcat** [comment]
Правильно ли я понимаю что вначале мы нажимаем на "Submit", а уже потом на нажатие "Fix"  перезаписываем эту же строчку?

**Comment by mytcat** [comment]
Time Estimation: 4hours

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v1.74
