### ISSUE TITLE
Автоматически очищать поля после «Submit»

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#31]
Автоматически очищать поля после нажатия кнопки «Submit», так как ручками очищать поля при открытии каждой новой ссылки нерационально.

И тогда возможно можно убрать кнопку **"Clean"**.

**Comment by mytcat** [comment]
Time Estimation: 15mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Fixed in v. 1.68
