### ISSUE TITLE
Повторное добавление компании-инвестора 

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#32]
При повторном добавлении компании инвестора в одно из полей "Lead Investors", "Partner Investors", "Investors" выскакивает всплывающее окно с некорректной ошибкой (названием ошибки).

<img width="1392" alt="Снимок экрана 2020-01-13 в 13 42 22" src="https://user-images.githubusercontent.com/36056528/72253686-c91e4b00-360a-11ea-88cf-a7d4f17b9bab.png">

Лучше выводить **«… already added!»** и всё.

_P.S._: возможно лучше добавить такую проверку для каждого поля таблицы, чтобы user не вносил дважды одни и те же данные в поле.

**Comment by mytcat** [comment]
Титул алёрта обязателен из соображений безопасности (фишинг и тд). Изменю его на читаемый вид: 
"<имя домена> says:
tag already added"

 Time Estimation: 15mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v. 1.68
