### ISSUE TITLE
Пробел перед текстом

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#34]
<img width="1392" alt="Снимок экрана 2020-01-10 в 19 11 12" src="https://user-images.githubusercontent.com/36056528/72257315-0509de00-3614-11ea-9444-b1803ed97df4.png">

При нажатии на тэг иногда автоматически появляется пробел перед текстом. Часто это поля **Company Name** и **Money Raised**.

**Comment by mytcat** [comment]
Time Estimation: 30mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Time: 15 mins

Done in v. 1.68
