### ISSUE TITLE
Checking data in dataset

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#38]
Check that the data from this press release (links) has **already been added** to the table (dataset).

- You can add a popup when you reopen a link (press release).
- Or add a pop-up window (or something else) already at the click of a button "Submit", but then the user will already do the extra unnecessary work.

**Comment by mytcat** [comment]
Time Estimation: 15mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v 1.70
