### ISSUE TITLE
No two identical fields

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#39]
Check that there are **no two identical fields (or rows)** in the table (dataset). Fields must not be duplicated.

**Comment by mytcat** [comment]
Time Estimation: 30mins

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
@ElizaLo 1. Этот энхенсмент https://github.com/mytcat/Form-to-google-spreadsheet/issues/38 не решит проблему текущей таски?
2. Когда в таблице будет много данных будет накладно проверять идентичность каждого поля.

**Comment by ElizaLo** [comment]
> @ElizaLo 1. Этот энхенсмент #38 не решит проблему текущей таски?
> 2. Когда в таблице будет много данных будет накладно проверять идентичность каждого поля.

Согласна, она может решить. Тогда пока не делай, если будет надобность, то сделаем.
