### ISSUE TITLE
Multiple Google-table entries

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#40]
If you press the button **"Submit"** several times (for example, 3), then the data will be entered into the Google-table several times (3 times it appears in the Google-table).

Even if the button "Submit" **_became green_**, when pressed again on it, the data is still entered into the Google-table.

<img width="1392" alt="Снимок экрана 2020-01-16 в 14 34 08" src="https://user-images.githubusercontent.com/36056528/72526321-db002800-386e-11ea-8fbc-231ddb3c9a76.png">

<img width="1392" alt="Снимок экрана 2020-01-16 в 14 37 04" src="https://user-images.githubusercontent.com/36056528/72526317-d89dce00-386e-11ea-8962-b1b9a454c593.png">

**Comment by mytcat** [comment]
Time Estimation: 15minutes

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v. 1.68
