### ISSUE TITLE
Disable scrolling up

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#41]
Needed to disable **scrolling up** when you click on a tag with a hyperlink. 
And disable the click on the link in the title of the article. 
For example, on [techcrunch.com](techcrunch.com), when you click on a tag in the title of an article, it goes to another page.

**Comment by mytcat** [comment]
Будет ли ок, если будут убираться все действующие ссылки на странице при клике на айкон экстеншена?

**Comment by ElizaLo** [comment]
Yes, it's okay.

**Comment by mytcat** [comment]
Time Estimation: 30minutes

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v. 1.68
