### ISSUE TITLE
Remove automatic "Not Defined"

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#42]
Needed to remove automatic filling the _**Clients Amount, Valuation, Revenue**_ fields with **"Not Defined"** if these fields are not filled in by the user in the table in the extension.

**Comment by mytcat** [comment]
Time Estimation: 15minutes

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v. 1.68
