### ISSUE TITLE
Parallel filling of tables in v. 1.69

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#48]
[Link 1](https://techcrunch.com/2012/01/15/online-marketplace-for-designer-fashion-boutiques-farfetch-raises-18m-from-index-ventures/)
<img width="1280" alt="Снимок экрана 2020-01-31 в 18 50 32" src="https://user-images.githubusercontent.com/36056528/73557903-c5882200-445a-11ea-8893-1f9f4c5b1a03.png">

[Link 2](https://www.businesswire.com/news/home/20150419005048/en/Rakuten-Invests-Leading-Chinese-Online-Rebates-Site)
<img width="1280" alt="Снимок экрана 2020-01-31 в 18 52 34" src="https://user-images.githubusercontent.com/36056528/73557974-ea7c9500-445a-11ea-9e9e-d6464f690254.png">

**Comment by mytcat** [comment]
Fixed in v1.74
