### ISSUE TITLE
Remove subscription-blocker

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#50]
Remove subscription-blocker on [Deal Street Asia](https://www.dealstreetasia.com/stories/chinese-music-education-platform-vip-peilian-snags-150m-series-c-110496/)

<img width="1392" alt="Снимок экрана 2020-01-31 в 21 36 22" src="https://user-images.githubusercontent.com/36056528/73569238-b01ef200-4472-11ea-80a0-e8ce8ceac0a8.png">

<img width="1392" alt="Снимок экрана 2020-01-31 в 21 42 00" src="https://user-images.githubusercontent.com/36056528/73569304-cdec5700-4472-11ea-9108-d2ca2c6dac69.png">

**Comment by mytcat** [comment]
Time Estimation: 15mins

**Comment by mytcat** [comment]
Done in v 1.70

**Comment by AlexUdodenko** [comment]
Approved
