### ISSUE TITLE
Remove a tale during copy-past

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#51]
Remove a tale during copy-past from [Deal Street Asia](https://www.dealstreetasia.com/stories/chinese-music-education-platform-vip-peilian-snags-150m-series-c-110496/)

Read more at: https://www.dealstreetasia.com/stories/chinese-music-education-platform-vip-peilian-snags-150m-series-c-110496/

<img width="1392" alt="Снимок экрана 2020-01-31 в 21 45 36" src="https://user-images.githubusercontent.com/36056528/73569457-2ae80d00-4473-11ea-9604-5e61a65bb02c.png">

**Comment by mytcat** [comment]
Time Estimation: 1h

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v1.74
