### ISSUE TITLE
Create a new Google-table for each user

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#52]
Для каждого нового пользователя расширения создавать новую Google-таблицу. Таблица должна быть привязана к email, который используется при скачивании расширения.

<img width="1280" alt="Снимок экрана 2020-02-04 в 21 41 39" src="https://user-images.githubusercontent.com/36056528/73780430-25523600-4797-11ea-90d3-3a30897656f1.png">

**Comment by mytcat** [comment]
@ElizaLo Должна быть отдельная таблица со своим id или достаточно в одном спредшите писать данные в свой лист ("Sheet1", "Sheet2", ...) для каждого юзера?

**Comment by ElizaLo** [comment]
> @ElizaLo Должна быть отдельная таблица со своим id или достаточно в одном спредшите писать данные в свой лист ("Sheet1", "Sheet2", ...) для каждого юзера?

Лучше писать данные в свой лист ("Sheet1", "Sheet2", ...) для каждого юзера.

**Comment by mytcat** [comment]
Time Estimation: 1.5h

**Comment by mytcat** [comment]
Done in v. 1.73
