### ISSUE TITLE
Wrong "Alert"

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#53]
![2020-02-06 13 46 17](https://user-images.githubusercontent.com/36056528/73934521-4c1f8200-48e7-11ea-94ce-5dd30a6971ad.jpg)
_________________________
![2020-02-06 13 42 34](https://user-images.githubusercontent.com/36056528/73934517-4aee5500-48e7-11ea-8148-5f1a45ad15c8.jpg)

**Comment by mytcat** [comment]
Fixed in v1.74
