### ISSUE TITLE
Check on a sheet, not about the whole table

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#54]
Ссылки параллельно обрабатывает несколько людей, поэтому важно, чтобы проверка была: **есть ли ссылка именно во вкладке (sheet) того пользователя, который заполняет, а не проверяло по всей таблице**.

<img width="1392" alt="Снимок экрана 2020-02-06 в 20 51 04" src="https://user-images.githubusercontent.com/36056528/73968583-9114da00-4922-11ea-8629-46545bb0bfba.png">

**Comment by mytcat** [comment]
Done
