### ISSUE TITLE
Disable tagging

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#56]
Disable tagging for chosen emails.

**Comment by mytcat** [comment]
![Screen Shot 2020-02-24 at 12 24 14 AM](https://user-images.githubusercontent.com/1709593/75121367-0e1eae00-569c-11ea-89c0-059082b3dfb8.png)

**Comment by mytcat** [comment]
Time Estimation: 0.5h

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v1.78
