### ISSUE TITLE
Remove a tale during copy-past

### ISSUE THREAD

**Issue by ElizaLo** [mytcat/Form-to-google-spreadsheet#57]
Remove a tale during copy-paste from [Businsess Insider](https://www.businessinsider.in) 

Read more at:
https://www.businessinsider.in/?utm_source=contentofinterest&utm_medium=text&utm_campaign=cppst

![photo_2020-02-21 21 39 57](https://user-images.githubusercontent.com/36056528/75066036-bb55c280-54f2-11ea-9ee8-b5fbe2b49924.jpeg)

**Comment by mytcat** [comment]
Time Estimation: 0.25h

**Comment by AlexUdodenko** [comment]
Approved

**Comment by mytcat** [comment]
Done in v1.78
